image: node:8.12.0

stages:
  - deploy

before_script:
  - npm i
  - npm run build

job_deploy:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_2" | tr -d '\r' | ssh-add - > /dev/null
    - rsync -avuz $CI_PROJECT_DIR/dist/ $SERVER_USER@agendei.io:/home/$SERVER_USER/beauty
  only:
    - master
